# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build
  jobs:
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndUbuntu1
      vmImage: 'ubuntu-latest'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndUbuntu2
      vmImage: 'ubuntu-latest'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndUbuntu3
      vmImage: 'ubuntu-latest'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndUbuntu4
      vmImage: 'ubuntu-latest'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndUbuntu5
      vmImage: 'ubuntu-latest'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndWindows1
      vmImage: 'vs2017-win2016'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndWindows2
      vmImage: 'vs2017-win2016'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndWindows3
      vmImage: 'vs2017-win2016'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndWindows4
      vmImage: 'vs2017-win2016'
  - template: templates/static-build-jobs-template.yml
    parameters:
      name: BuildFrontEndWindows5
      vmImage: 'vs2017-win2016'


  # - job: Linux
  #   pool:
  #     vmImage: 'ubuntu-latest'
  #   steps:
  #   - task: NodeTool@0
  #     inputs:
  #       versionSpec: '10.x'
  #     displayName: 'Install Node.js'

  #   - script: |
  #       cd fitness/app
  #       npm install
  #       npm run jss build
  #   #    npm run jss "setup --instancePath c:\bla --layoutServiceHost https://sitecore9 --apiKey bla"
  #     displayName: 'npm install and jss setup'

  #   - task: PublishPipelineArtifact@0
  #     inputs:
  #       artifactName: 'drop1' 
  #       targetPath: fitness/app/build/ 

- stage: DeployTest
  dependsOn: Build
  jobs:
  - deployment: DeployTest1
    pool:
      vmImage: 'vs2017-win2016'
    environment: Test environment 1 - CD
    strategy:
      runOnce:
        deploy: 
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
              sleep 60
            displayName: 'Run a multi-line script'
   
  - deployment: DeployTest2
    pool:
      vmImage: 'vs2017-win2016'
    environment: Test environment 1 - CM
    strategy:
      runOnce:
        deploy: 
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
              sleep 60
            displayName: 'Run a multi-line script'

- stage: DeployParallelTests
  dependsOn: Build
  jobs:
  - deployment: ParallelTest
    pool:
      vmImage: 'vs2017-win2016'
    environment: Test environment 2
    strategy:
      runOnce:
        deploy: 
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'

- stage: QA
  dependsOn: 
  - DeployTest
  - DeployParallelTests
  jobs:
  - deployment: QA
    pool:
      vmImage: 'vs2017-win2016'
    environment: QA Environment
    strategy:
      runOnce:
        deploy: 
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'





