parameters:
  name: ''
  vmImage: ''
  artifactName: ''

jobs:
- job: '${{ parameters.name }}'
  pool:
    vmImage: '${{ parameters.vmImage }}'
  steps:
  - template: static-build-steps-template.yml
    parameters: 
      artifactName: '${{ parameters.artifactName }}'